Redoing Add-Tenant PR
open-austin/BASTA-tfwa pull request #163
Opened 2021-04-17 21:57 UTC by minpat

2021-05-16 21:02 UTC, minpat commented
Hey @JamesBock - could you please check this when you have a chance?  The mutation works now in terms of referencing the propertyId and has no errors.  However, I found that if you query the tenant list after adding an item, it shows the propertyId as being null.  Here is the query.  Thanks.

`query getTenants {
  tenants {
    nodes {
      id
      name
      residence {
        propertyId
        address {
          line1
        }
      }
    }
  }
}`

2021-05-17 00:37 UTC, JamesBock commented
> Hey @JamesBock - could you please check this when you have a chance? The mutation works now in terms of referencing the propertyId and has no errors. However, I found that if you query the tenant list after adding an item, it shows the propertyId as being null. Here is the query. Thanks.
> 
> `query getTenants { tenants { nodes { id name residence { propertyId address { line1 } } } } }`

This is something I need to add to the TenantMutations. The PropertyId is not being assigned from the TenantInput. Will add to my PR

2021-05-17 00:56 UTC, minpat commented
Ok - sounds good - thanks.

2021-05-21 01:11 UTC, JamesBock requested changes
A few things to clean up. I'm not getting the query to fire so the properties are always null and nothing shows. Let me know if you want to look at this sometime.

2021-05-21 01:11 UTC, JamesBock commented on tenant-file/portal-app/src/component/add-tenant.tsx
> +// Credit to the Formik documentation - this was largely copied from an example there
You can remove this

2021-05-21 01:11 UTC, JamesBock commented on tenant-file/portal-app/src/component/add-tenant.tsx
> +    const { loading, data } = useQuery(GET_PROPERTIES);
Is this executing for you locally? It is never firing for me.

2021-05-23 01:08 UTC, JamesBock commented on tenant-file/portal-app/src/component/add-tenant.tsx
> +    const { loading, data } = useQuery(GET_PROPERTIES);
I actually didn't have a url set for the apollo client. Works once it is set.

2021-05-23 01:28 UTC, JamesBock commented
> A few things to clean up. I'm not getting the query to fire so the properties are always null and nothing shows. Let me know if you want to look at this sometime.

After adding the uri for the ApolloProvider and integrating the changes needed on the backend I made in my recent PR, I was able to add a Tenant, create them a new Residence and assign the Residence to a Property all that the add-tenant page. So this is actually pretty close to being ready. Just need to clean up the data mapping.

2021-05-23 01:30 UTC, JamesBock commented on tenant-file/portal-app/src/component/add-tenant.tsx
> +        createTenant(inputTenant: { name: $fullName, phoneNumber: $phoneNumber, currentResidence: { addressInput: { line1: $street, city: $city, state: "TX", postalCode: $zip }, propertyId: $bldgId }
We need to map the apartment number with Line2 of the address type to be in line with the USPS standard

2021-05-23 17:13 UTC, JamesBock approved these changes
This is working for me with the backend changes from my PR. Unit number is mapping to line2 appropriately.

2021-05-23 17:17 UTC, merged